### ISSUE TITLE
New XR Plugin system - OpenXR support.

### ISSUE THREAD

**Issue by ninlilizi** [koochyrat/SteamVRFrustumAdjust#4]
Unity is now moving towards OpenXR.

Is it possible to update this to add OpenXR support using Unitys' new XR plugin system?

I've attempted to do so myself, but have been unable to discover how to access the required hmd raw projection matrix and fov values using the OpenXR API. I've had a good poke around the API and it seems to fall short in directly exposing any useful information with respect to the attached HMD.

**Comment by koochyrat** [comment]
I haven't had the chance to update it to OpenXR yet, but you might be able to get by with Unity's Tracked pose driver getting the left/right eye and head and then you should be able figure out the rotation relative to the head. Yeah, Unity doesn't expose the entire API unfortunately.

**Comment by ninlilizi** [comment]
The is unfortunate.

My next thought was, as OpenXR allows people to create their own extention 'features'.
( https://docs.unity3d.com/Packages/com.unity.xr.openxr@0.1/manual/features.html )

it could be possible to create a OpenXR feature in this way have have it make a call to a native DLL, the same way you did with the OpenVR support.

I am certainly not a noob to programming, so my challenge would be figuring out which DLL and what to call. I'm going to have a poke at figuring that out when I have time. But if you have any insight that may help me narrow down my search quicker, it could help.

**Comment by koochyrat** [comment]
You can try https://github.com/dotnet/Silk.NET which has C# OpenXR bindings. Not sure if it will work in Unity, but worth a shot.

**Comment by koochyrat** [comment]
Ok, after some reading up I think I know how to access the entire API in Unity now. OpenXRFeature.xrGetInstanceProcAddr allows you to get the IntPtr which then can be stuffed into a method signature declared in C#. Will give it a shot soon.

**Comment by koochyrat** [comment]
Ok, done.
